#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "auth_service.pb.h"

namespace AuthService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void Register(RegisterReq *request, AuthResp *response,
					srpc::RPCContext *ctx) = 0;

	virtual void Login(LoginReq *request, AuthResp *response,
					srpc::RPCContext *ctx) = 0;

	virtual void VerifyToken(VerifyTokenReq *request, VerifyTokenResp *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using RegisterDone = std::function<void (AuthResp *, srpc::RPCContext *)>;
using LoginDone = std::function<void (AuthResp *, srpc::RPCContext *)>;
using VerifyTokenDone = std::function<void (VerifyTokenResp *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void Register(const RegisterReq *req, RegisterDone done);
	void Register(const RegisterReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> async_Register(const RegisterReq *req);

	void Login(const LoginReq *req, LoginDone done);
	void Login(const LoginReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> async_Login(const LoginReq *req);

	void VerifyToken(const VerifyTokenReq *req, VerifyTokenDone done);
	void VerifyToken(const VerifyTokenReq *req, VerifyTokenResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyTokenResp, srpc::RPCSyncContext>> async_VerifyToken(const VerifyTokenReq *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_Register_task(RegisterDone done);
	srpc::SRPCClientTask *create_Login_task(LoginDone done);
	srpc::SRPCClientTask *create_VerifyToken_task(VerifyTokenDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void Register(const RegisterReq *req, RegisterDone done);
	void Register(const RegisterReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> async_Register(const RegisterReq *req);

	void Login(const LoginReq *req, LoginDone done);
	void Login(const LoginReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> async_Login(const LoginReq *req);

	void VerifyToken(const VerifyTokenReq *req, VerifyTokenDone done);
	void VerifyToken(const VerifyTokenReq *req, VerifyTokenResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyTokenResp, srpc::RPCSyncContext>> async_VerifyToken(const VerifyTokenReq *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_Register_task(RegisterDone done);
	srpc::SRPCHttpClientTask *create_Login_task(LoginDone done);
	srpc::SRPCHttpClientTask *create_VerifyToken_task(VerifyTokenDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void Register(const RegisterReq *req, RegisterDone done);
	void Register(const RegisterReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> async_Register(const RegisterReq *req);

	void Login(const LoginReq *req, LoginDone done);
	void Login(const LoginReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> async_Login(const LoginReq *req);

	void VerifyToken(const VerifyTokenReq *req, VerifyTokenDone done);
	void VerifyToken(const VerifyTokenReq *req, VerifyTokenResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyTokenResp, srpc::RPCSyncContext>> async_VerifyToken(const VerifyTokenReq *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_Register_task(RegisterDone done);
	srpc::BRPCClientTask *create_Login_task(LoginDone done);
	srpc::BRPCClientTask *create_VerifyToken_task(VerifyTokenDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void Register(const RegisterReq *req, RegisterDone done);
	void Register(const RegisterReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> async_Register(const RegisterReq *req);

	void Login(const LoginReq *req, LoginDone done);
	void Login(const LoginReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> async_Login(const LoginReq *req);

	void VerifyToken(const VerifyTokenReq *req, VerifyTokenDone done);
	void VerifyToken(const VerifyTokenReq *req, VerifyTokenResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyTokenResp, srpc::RPCSyncContext>> async_VerifyToken(const VerifyTokenReq *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_Register_task(RegisterDone done);
	srpc::TRPCClientTask *create_Login_task(LoginDone done);
	srpc::TRPCClientTask *create_VerifyToken_task(VerifyTokenDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void Register(const RegisterReq *req, RegisterDone done);
	void Register(const RegisterReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> async_Register(const RegisterReq *req);

	void Login(const LoginReq *req, LoginDone done);
	void Login(const LoginReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> async_Login(const LoginReq *req);

	void VerifyToken(const VerifyTokenReq *req, VerifyTokenDone done);
	void VerifyToken(const VerifyTokenReq *req, VerifyTokenResp *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyTokenResp, srpc::RPCSyncContext>> async_VerifyToken(const VerifyTokenReq *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_Register_task(RegisterDone done);
	srpc::TRPCHttpClientTask *create_Login_task(LoginDone done);
	srpc::TRPCHttpClientTask *create_VerifyToken_task(VerifyTokenDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("AuthService")
{
	this->srpc::RPCService::add_method("Register",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Register);
		});

	this->srpc::RPCService::add_method("Login",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Login);
		});

	this->srpc::RPCService::add_method("VerifyToken",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::VerifyToken);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::Register(const RegisterReq *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Register(const RegisterReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> SRPCClient::async_Register(const RegisterReq *req)
{
	using RESULT = std::pair<AuthResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<AuthResp>("Register", srpc::RPCAsyncFutureCallback<AuthResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::Login(const LoginReq *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Login(const LoginReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> SRPCClient::async_Login(const LoginReq *req)
{
	using RESULT = std::pair<AuthResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<AuthResp>("Login", srpc::RPCAsyncFutureCallback<AuthResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::VerifyToken(const VerifyTokenReq *req, VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("VerifyToken", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::VerifyToken(const VerifyTokenReq *req, VerifyTokenResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_VerifyToken(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyTokenResp, srpc::RPCSyncContext>> SRPCClient::async_VerifyToken(const VerifyTokenReq *req)
{
	using RESULT = std::pair<VerifyTokenResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyTokenResp>("VerifyToken", srpc::RPCAsyncFutureCallback<VerifyTokenResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_Register_task(RegisterDone done)
{
	return this->create_rpc_client_task("Register", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_Login_task(LoginDone done)
{
	return this->create_rpc_client_task("Login", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_VerifyToken_task(VerifyTokenDone done)
{
	return this->create_rpc_client_task("VerifyToken", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::Register(const RegisterReq *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Register(const RegisterReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> SRPCHttpClient::async_Register(const RegisterReq *req)
{
	using RESULT = std::pair<AuthResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<AuthResp>("Register", srpc::RPCAsyncFutureCallback<AuthResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::Login(const LoginReq *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Login(const LoginReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> SRPCHttpClient::async_Login(const LoginReq *req)
{
	using RESULT = std::pair<AuthResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<AuthResp>("Login", srpc::RPCAsyncFutureCallback<AuthResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::VerifyToken(const VerifyTokenReq *req, VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("VerifyToken", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::VerifyToken(const VerifyTokenReq *req, VerifyTokenResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_VerifyToken(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyTokenResp, srpc::RPCSyncContext>> SRPCHttpClient::async_VerifyToken(const VerifyTokenReq *req)
{
	using RESULT = std::pair<VerifyTokenResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyTokenResp>("VerifyToken", srpc::RPCAsyncFutureCallback<VerifyTokenResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Register_task(RegisterDone done)
{
	return this->create_rpc_client_task("Register", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Login_task(LoginDone done)
{
	return this->create_rpc_client_task("Login", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_VerifyToken_task(VerifyTokenDone done)
{
	return this->create_rpc_client_task("VerifyToken", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::Register(const RegisterReq *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Register(const RegisterReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> BRPCClient::async_Register(const RegisterReq *req)
{
	using RESULT = std::pair<AuthResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<AuthResp>("Register", srpc::RPCAsyncFutureCallback<AuthResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::Login(const LoginReq *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Login(const LoginReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> BRPCClient::async_Login(const LoginReq *req)
{
	using RESULT = std::pair<AuthResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<AuthResp>("Login", srpc::RPCAsyncFutureCallback<AuthResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::VerifyToken(const VerifyTokenReq *req, VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("VerifyToken", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::VerifyToken(const VerifyTokenReq *req, VerifyTokenResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_VerifyToken(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyTokenResp, srpc::RPCSyncContext>> BRPCClient::async_VerifyToken(const VerifyTokenReq *req)
{
	using RESULT = std::pair<VerifyTokenResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyTokenResp>("VerifyToken", srpc::RPCAsyncFutureCallback<VerifyTokenResp>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_Register_task(RegisterDone done)
{
	return this->create_rpc_client_task("Register", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_Login_task(LoginDone done)
{
	return this->create_rpc_client_task("Login", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_VerifyToken_task(VerifyTokenDone done)
{
	return this->create_rpc_client_task("VerifyToken", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::Register(const RegisterReq *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("/AuthService/Register", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Register(const RegisterReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> TRPCClient::async_Register(const RegisterReq *req)
{
	using RESULT = std::pair<AuthResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<AuthResp>("/AuthService/Register", srpc::RPCAsyncFutureCallback<AuthResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::Login(const LoginReq *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("/AuthService/Login", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Login(const LoginReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> TRPCClient::async_Login(const LoginReq *req)
{
	using RESULT = std::pair<AuthResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<AuthResp>("/AuthService/Login", srpc::RPCAsyncFutureCallback<AuthResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::VerifyToken(const VerifyTokenReq *req, VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("/AuthService/VerifyToken", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::VerifyToken(const VerifyTokenReq *req, VerifyTokenResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_VerifyToken(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyTokenResp, srpc::RPCSyncContext>> TRPCClient::async_VerifyToken(const VerifyTokenReq *req)
{
	using RESULT = std::pair<VerifyTokenResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyTokenResp>("/AuthService/VerifyToken", srpc::RPCAsyncFutureCallback<VerifyTokenResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_Register_task(RegisterDone done)
{
	auto *task = this->create_rpc_client_task("/AuthService/Register", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_Login_task(LoginDone done)
{
	auto *task = this->create_rpc_client_task("/AuthService/Login", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_VerifyToken_task(VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("/AuthService/VerifyToken", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::Register(const RegisterReq *req, RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Register(const RegisterReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Register(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> TRPCHttpClient::async_Register(const RegisterReq *req)
{
	using RESULT = std::pair<AuthResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<AuthResp>("Register", srpc::RPCAsyncFutureCallback<AuthResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::Login(const LoginReq *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Login(const LoginReq *req, AuthResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<AuthResp, srpc::RPCSyncContext>> TRPCHttpClient::async_Login(const LoginReq *req)
{
	using RESULT = std::pair<AuthResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<AuthResp>("Login", srpc::RPCAsyncFutureCallback<AuthResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::VerifyToken(const VerifyTokenReq *req, VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("VerifyToken", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::VerifyToken(const VerifyTokenReq *req, VerifyTokenResp *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_VerifyToken(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyTokenResp, srpc::RPCSyncContext>> TRPCHttpClient::async_VerifyToken(const VerifyTokenReq *req)
{
	using RESULT = std::pair<VerifyTokenResp, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyTokenResp>("VerifyToken", srpc::RPCAsyncFutureCallback<VerifyTokenResp>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Register_task(RegisterDone done)
{
	auto *task = this->create_rpc_client_task("Register", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Login_task(LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_VerifyToken_task(VerifyTokenDone done)
{
	auto *task = this->create_rpc_client_task("VerifyToken", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace AuthService

